disabled = false
languageCode = "en"
languageName = "English"
weight = 1

baseURL = "https://www.bytecascade.online/"

title = "ByteCascade"
description = "ByteCascade Technology Reviews delivers the latest tech news, gadget reviews, Android updates, and in-depth guides since 2023."

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  copyright = "&copy; 2023–{ year } iSamuel"

  [params.homepage]
    layout = "profile"
    showRecent = true

[params.author]
  name = "iSamuel"
  email = "bytecascade11@gmail.com"
  headline = "Technology Reviews, Android Updates, and In-Depth Guides"
  bio = "I’m Oke Sunday Samuel (most people call me iSamuel). I study Physics & Electronics and write practical, expert technology analysis and insights for real people in Nigeria and beyond."

  links = [
    { email = "mailto:bytecascade11@gmail.com" },     
    { link = "https://www.revibyte.blog/" },
    { blogger = "https://bytecascade.blogspot.com/" },
    { x-twitter = "https://x.com/ByteCascade1" },
    { youtube = "https://youtube.com/@bytecascade1?si=bufIL0nGCduayqPo" },
    { telegram = "https://t.me/bytecascade" },
    { github = "https://github.com/bytecascade11" }
  ]
