# -- Main Menu (Top Navigation) --u

[[main]]
  name = "News"
  pageRef = "/categories/news/"     # Create this category for news posts
  weight = 10

[[main]]
  name = "Samsung"
  pageRef = "/categories/samsung/"
  weight = 20

[[main]]
  name = "Apple"
  pageRef = "/categories/apple/"
  weight = 30
  
[[main]]
  name = "Android"
  pageRef = "/categories/android/"
  weight = 35
  
[[main]]
  name = "AI"
  pageRef = "/categories/ai/"
  weight = 40

[[main]]
  name = "Games"
  pageRef = "/categories/games/"
  weight = 50

[[main]]
  name = "Reviews"
  pageRef = "/categories/reviews/"
  weight = 60


# -- Footer Menu --

[[footer]]
  name = "Tags"
  pageRef = "/tags/"
  weight = 70
  
[[footer]]
  name = "About Us"
  pageRef = "/about-us/"
  weight = 10

[[footer]]
  name = "Contact Us"
  pageRef = "/contact-us/"
  weight = 20

[[footer]]
  name = "Privacy Policy"
  pageRef = "/privacy-policy/"
  weight = 30

[[footer]]
  name = "Terms and Conditions"
  pageRef = "/terms-and-conditions/"
  weight = 40

[[footer]]
  name = "Disclaimer"
  pageRef = "/disclaimer/"
  weight = 50

  [[footer]]
  name = "Sitemap"
  pageRef = "/sitemap/"
  weight = 80   # Higher than Tags (70) so it appears after
